#!/usr/bin/perl -w
#
# This is an example of a subclass of the generated application
#
# You can safely edit this file, any changes that you make will be preserved
# and this file will not be overwritten by the next run of Glade::PerlGenerate
#
#==============================================================================
#=== This is the 'Subabout' class                              
#==============================================================================
package Subabout;
require 5.000; use strict 'vars', 'refs', 'subs';
# UI class 'Subabout' (version 0.01)
# 
# Copyright (c) Date 週五 11月  1 15:18:17 CST 2002
# Author  <allways@allways.taipei.excell.com.tw>
#
# Unspecified copying policy, please contact the author
#  <allways@allways.taipei.excell.com.tw>
#
#==============================================================================
# This perl source file was automatically generated by 
# Glade::PerlGenerate version 0.60 - Fri May  3 03:56:25 BST 2002
# Copyright (c) Author Dermot Musgrove <dermot.musgrove@virgin.net>
#
# from Glade file /home/allways/Projects/print_scale/print_scale.glade
# 週五 11月  1 15:18:17 CST 2002
#==============================================================================

BEGIN {
    use vars qw( 
                 @ISA
                 %fields
                 $PACKAGE
                 $VERSION
                 $AUTHOR
                 $DATE
                 $permitted_fields
             );
    # Existing signal handler modules
    use src::print_scale;
    # We need the Gnome bindings as well
    use Gnome;
    # Uncomment the line below to enable gettext checking
#    use Glade::PerlSource;
    # Tell interpreter who we are inheriting from
    @ISA     = qw( about );
    # Uncomment the line below to enable gettext checking
#    @ISA      = qw( about Glade::PerlSource );
    $PACKAGE = 'Subprint_scale';
    $VERSION = '0.01';
    $AUTHOR  = ' <allways@allways.taipei.excell.com.tw>';
    $DATE    = '週五 11月  1 15:18:17 CST 2002';
    $permitted_fields = '_permitted_fields';             
    # Inherit the AUTOLOAD dynamic methods from about
    *AUTOLOAD = \&about::AUTOLOAD;
} # End of sub BEGIN

%fields = (
# Insert any extra data access methods that you want to add to 
#   our inherited super-constructor (or overload)
    USERDATA    => undef,
    VERSION     => '0.10',
);

sub DESTROY {
    # This sub will be called on object destruction
} # End of sub DESTROY

#==============================================================================
#=== Below are the overloaded class constructors
#==============================================================================
sub new {
    my $that  = shift;
    # Allow indirect constructor so that we can call eg. 
    #   $window1 = Frame->new; $window2 = $window1->new;
    my $class = ref($that) || $that;

    # Call our super-class constructor to get an object and reconsecrate it
    my $self = bless $that->SUPER::new(), $class;

    # Add our own data access methods to the inherited constructor
    my($element);
    foreach $element (keys %fields) {
        $self->{$permitted_fields}->{$element} = $fields{$element};
    }
    @{$self}{keys %fields} = values %fields;
    return $self;
} # End of sub new

sub app_run {
    my ($class, %params) = @_;
    Gnome->init('print_scale', '0.01');
    # Uncomment the line below to enable gettext checking
#    $class->check_gettext_strings;
    my $window = $class->new;
    # Insert your subclass user data key/value pairs 
    $window->USERDATA({
#        'Key1'   => 'Value1',
#        'Key2'   => 'Value2',
#        'Key3'   => 'Value3',
    });
    $window->TOPLEVEL->show;
#    my $window2 = $window->new;
#    $window2->TOPLEVEL->show;
    Gtk->main;
    # Uncomment the line below to enable gettext checking
#    $window->write_gettext_strings("__", '/home/allways/Projects/print_scale/src/print_scale.pot');
    $window->TOPLEVEL->destroy;

    return $window;
} # End of sub run
#===============================================================================
#=== Below are (overloaded) default signal handlers for 'about' class 
#===============================================================================
sub about_Form {
    my ($class) = @_;
    my $gtkversion = 
        Gtk->major_version.".".
        Gtk->minor_version.".".
        Gtk->micro_version;
    my $name = $0;
    #
    # Create a Gnome::About '$ab'
    my $ab = new Gnome::About(
        $PACKAGE, 
        $VERSION, 
        _("Copyright")." $DATE", 
        $AUTHOR, 
        _('No description')."\n".
        "Gtk ".     _("version").": $gtkversion\n".
        "Gtk-Perl "._("version").": $Gtk::VERSION\n".
        `gnome-config --version`."\n".
        _("run from file").": $name\n \n".
        '# Unspecified copying policy, please contact the author
#', 
        "$Glade::PerlRun::pixmaps_directory/Logo.xpm", 
    );
    $ab->set_title(_("About")." Subprint_scale" );
    $ab->position('mouse' );
    $ab->set_policy(1, 1, 0 );
    $ab->set_modal(1 );
    $ab->show;
} # End of sub about_Form

sub destroy_Form {
    my ($class, $data, $object, $instance) = @_;
    Gtk->main_quit; 
} # End of sub destroy_Form

sub toplevel_hide    { shift->get_toplevel->hide    }
sub toplevel_close   { shift->get_toplevel->close   }
sub toplevel_destroy { shift->get_toplevel->destroy }

#==============================================================================
#=== Below are (overloaded) signal handlers for 'about' class 
#==============================================================================
sub on_about_button_clicked {
    my ($class, $data, $object, $instance, $event) = @_;
    my $me = __PACKAGE__."->on_about_button_clicked";
    # Get ref to hash of all widgets on our form
    my $form = $__PACKAGE__::all_forms->{$instance};

    # REPLACE the lines below with the actions to be taken when __PACKAGE__."->on_about_button_clicked." is called
#    __PACKAGE__->show_skeleton_message($me, \@_, __PACKAGE__, "$Glade::PerlRun::pixmaps_directory/Logo.xpm");
    shift->SUPER::on_about_button_clicked(@_);

} # End of sub on_about_button_clicked

sub on_about_delete_event {
    my ($class, $data, $object, $instance, $event) = @_;
    my $me = __PACKAGE__."->on_about_delete_event";
    # Get ref to hash of all widgets on our form
    my $form = $__PACKAGE__::all_forms->{$instance};

    # REPLACE the lines below with the actions to be taken when __PACKAGE__."->on_about_delete_event." is called
#    __PACKAGE__->show_skeleton_message($me, \@_, __PACKAGE__, "$Glade::PerlRun::pixmaps_directory/Logo.xpm");
    shift->SUPER::on_about_delete_event(@_);

} # End of sub on_about_delete_event










#==============================================================================
#=== This is the 'Submain' class                              
#==============================================================================
package Submain;
require 5.000; use strict 'vars', 'refs', 'subs';
# UI class 'Submain' (version 0.01)
# 
# Copyright (c) Date 週五 11月  1 15:18:17 CST 2002
# Author  <allways@allways.taipei.excell.com.tw>
#
# Unspecified copying policy, please contact the author
#  <allways@allways.taipei.excell.com.tw>
#
#==============================================================================
# This perl source file was automatically generated by 
# Glade::PerlGenerate version 0.60 - Fri May  3 03:56:25 BST 2002
# Copyright (c) Author Dermot Musgrove <dermot.musgrove@virgin.net>
#
# from Glade file /home/allways/Projects/print_scale/print_scale.glade
# 週五 11月  1 15:18:17 CST 2002
#==============================================================================

BEGIN {
    use vars qw( 
                 @ISA
                 %fields
                 $PACKAGE
                 $VERSION
                 $AUTHOR
                 $DATE
                 $permitted_fields
             );
    # Existing signal handler modules
    use src::print_scale;
    # We need the Gnome bindings as well
    use Gnome;
    # Uncomment the line below to enable gettext checking
#    use Glade::PerlSource;
    # Tell interpreter who we are inheriting from
    @ISA     = qw( main );
    # Uncomment the line below to enable gettext checking
#    @ISA      = qw( main Glade::PerlSource );
    $PACKAGE = 'Subprint_scale';
    $VERSION = '0.01';
    $AUTHOR  = ' <allways@allways.taipei.excell.com.tw>';
    $DATE    = '週五 11月  1 15:18:17 CST 2002';
    $permitted_fields = '_permitted_fields';             
    # Inherit the AUTOLOAD dynamic methods from main
    *AUTOLOAD = \&main::AUTOLOAD;
} # End of sub BEGIN

%fields = (
# Insert any extra data access methods that you want to add to 
#   our inherited super-constructor (or overload)
    USERDATA    => undef,
    VERSION     => '0.10',
);

sub DESTROY {
    # This sub will be called on object destruction
} # End of sub DESTROY

#==============================================================================
#=== Below are the overloaded class constructors
#==============================================================================
sub new {
    my $that  = shift;
    # Allow indirect constructor so that we can call eg. 
    #   $window1 = Frame->new; $window2 = $window1->new;
    my $class = ref($that) || $that;

    # Call our super-class constructor to get an object and reconsecrate it
    my $self = bless $that->SUPER::new(), $class;

    # Add our own data access methods to the inherited constructor
    my($element);
    foreach $element (keys %fields) {
        $self->{$permitted_fields}->{$element} = $fields{$element};
    }
    @{$self}{keys %fields} = values %fields;
    return $self;
} # End of sub new

sub app_run {
    my ($class, %params) = @_;
    Gnome->init('print_scale', '0.01');
    # Uncomment the line below to enable gettext checking
#    $class->check_gettext_strings;
    my $window = $class->new;
    # Insert your subclass user data key/value pairs 
    $window->USERDATA({
#        'Key1'   => 'Value1',
#        'Key2'   => 'Value2',
#        'Key3'   => 'Value3',
    });
    $window->TOPLEVEL->show;
#    my $window2 = $window->new;
#    $window2->TOPLEVEL->show;
    Gtk->main;
    # Uncomment the line below to enable gettext checking
#    $window->write_gettext_strings("__", '/home/allways/Projects/print_scale/src/print_scale.pot');
    $window->TOPLEVEL->destroy;

    return $window;
} # End of sub run
#===============================================================================
#=== Below are (overloaded) default signal handlers for 'main' class 
#===============================================================================
sub about_Form {
    my ($class) = @_;
    my $gtkversion = 
        Gtk->major_version.".".
        Gtk->minor_version.".".
        Gtk->micro_version;
    my $name = $0;
    #
    # Create a Gnome::About '$ab'
    my $ab = new Gnome::About(
        $PACKAGE, 
        $VERSION, 
        _("Copyright")." $DATE", 
        $AUTHOR, 
        _('No description')."\n".
        "Gtk ".     _("version").": $gtkversion\n".
        "Gtk-Perl "._("version").": $Gtk::VERSION\n".
        `gnome-config --version`."\n".
        _("run from file").": $name\n \n".
        '# Unspecified copying policy, please contact the author
#', 
        "$Glade::PerlRun::pixmaps_directory/Logo.xpm", 
    );
    $ab->set_title(_("About")." Subprint_scale" );
    $ab->position('mouse' );
    $ab->set_policy(1, 1, 0 );
    $ab->set_modal(1 );
    $ab->show;
} # End of sub about_Form

sub destroy_Form {
    my ($class, $data, $object, $instance) = @_;
    Gtk->main_quit; 
} # End of sub destroy_Form

sub toplevel_hide    { shift->get_toplevel->hide    }
sub toplevel_close   { shift->get_toplevel->close   }
sub toplevel_destroy { shift->get_toplevel->destroy }

#==============================================================================
#=== Below are (overloaded) signal handlers for 'main' class 
#==============================================================================
sub on_about_activate {
    my ($class, $data, $object, $instance, $event) = @_;
    my $me = __PACKAGE__."->on_about_activate";
    # Get ref to hash of all widgets on our form
    my $form = $__PACKAGE__::all_forms->{$instance};

    # REPLACE the lines below with the actions to be taken when __PACKAGE__."->on_about_activate." is called
#    __PACKAGE__->show_skeleton_message($me, \@_, __PACKAGE__, "$Glade::PerlRun::pixmaps_directory/Logo.xpm");
    shift->SUPER::on_about_activate(@_);

} # End of sub on_about_activate

sub on_button1_clicked {
    my ($class, $data, $object, $instance, $event) = @_;
    my $me = __PACKAGE__."->on_button1_clicked";
    # Get ref to hash of all widgets on our form
    my $form = $__PACKAGE__::all_forms->{$instance};

    # REPLACE the lines below with the actions to be taken when __PACKAGE__."->on_button1_clicked." is called
#    __PACKAGE__->show_skeleton_message($me, \@_, __PACKAGE__, "$Glade::PerlRun::pixmaps_directory/Logo.xpm");
    shift->SUPER::on_button1_clicked(@_);

} # End of sub on_button1_clicked

sub on_button2_clicked {
    my ($class, $data, $object, $instance, $event) = @_;
    my $me = __PACKAGE__."->on_button2_clicked";
    # Get ref to hash of all widgets on our form
    my $form = $__PACKAGE__::all_forms->{$instance};

    # REPLACE the lines below with the actions to be taken when __PACKAGE__."->on_button2_clicked." is called
#    __PACKAGE__->show_skeleton_message($me, \@_, __PACKAGE__, "$Glade::PerlRun::pixmaps_directory/Logo.xpm");
    shift->SUPER::on_button2_clicked(@_);

} # End of sub on_button2_clicked

sub on_button3_clicked {
    my ($class, $data, $object, $instance, $event) = @_;
    my $me = __PACKAGE__."->on_button3_clicked";
    # Get ref to hash of all widgets on our form
    my $form = $__PACKAGE__::all_forms->{$instance};

    # REPLACE the lines below with the actions to be taken when __PACKAGE__."->on_button3_clicked." is called
#    __PACKAGE__->show_skeleton_message($me, \@_, __PACKAGE__, "$Glade::PerlRun::pixmaps_directory/Logo.xpm");
    shift->SUPER::on_button3_clicked(@_);

} # End of sub on_button3_clicked

sub on_exit_activate {
    my ($class, $data, $object, $instance, $event) = @_;
    my $me = __PACKAGE__."->on_exit_activate";
    # Get ref to hash of all widgets on our form
    my $form = $__PACKAGE__::all_forms->{$instance};

    # REPLACE the lines below with the actions to be taken when __PACKAGE__."->on_exit_activate." is called
#    __PACKAGE__->show_skeleton_message($me, \@_, __PACKAGE__, "$Glade::PerlRun::pixmaps_directory/Logo.xpm");
    shift->SUPER::on_exit_activate(@_);

} # End of sub on_exit_activate

sub on_login_activate {
    my ($class, $data, $object, $instance, $event) = @_;
    my $me = __PACKAGE__."->on_login_activate";
    # Get ref to hash of all widgets on our form
    my $form = $__PACKAGE__::all_forms->{$instance};

    # REPLACE the lines below with the actions to be taken when __PACKAGE__."->on_login_activate." is called
#    __PACKAGE__->show_skeleton_message($me, \@_, __PACKAGE__, "$Glade::PerlRun::pixmaps_directory/Logo.xpm");
    shift->SUPER::on_login_activate(@_);

} # End of sub on_login_activate

sub on_logout_activate {
    my ($class, $data, $object, $instance, $event) = @_;
    my $me = __PACKAGE__."->on_logout_activate";
    # Get ref to hash of all widgets on our form
    my $form = $__PACKAGE__::all_forms->{$instance};

    # REPLACE the lines below with the actions to be taken when __PACKAGE__."->on_logout_activate." is called
#    __PACKAGE__->show_skeleton_message($me, \@_, __PACKAGE__, "$Glade::PerlRun::pixmaps_directory/Logo.xpm");
    shift->SUPER::on_logout_activate(@_);

} # End of sub on_logout_activate

sub on_window1_delete_event {
    my ($class, $data, $object, $instance, $event) = @_;
    my $me = __PACKAGE__."->on_window1_delete_event";
    # Get ref to hash of all widgets on our form
    my $form = $__PACKAGE__::all_forms->{$instance};

    # REPLACE the lines below with the actions to be taken when __PACKAGE__."->on_window1_delete_event." is called
#    __PACKAGE__->show_skeleton_message($me, \@_, __PACKAGE__, "$Glade::PerlRun::pixmaps_directory/Logo.xpm");
    shift->SUPER::on_window1_delete_event(@_);

} # End of sub on_window1_delete_event











1;

__END__

#===============================================================================
#==== Documentation
#===============================================================================
=pod

=head1 NAME

Subprint_scale - version 0.01 週五 11月  1 15:18:17 CST 2002

No description

=head1 SYNOPSIS

 use Subprint_scale;

 To construct the window object and show it call
 
 Gtk->init;
 my $window = Submain->new;
 $window->TOPLEVEL->show;
 Gtk->main;
 
 OR use the shorthand for the above calls
 
 Submain->app_run;

=head1 DESCRIPTION

Unfortunately, the author has not yet written any documentation :-(

=head1 AUTHOR

 <allways@allways.taipei.excell.com.tw>

=cut
